In [2]:
import pandas as pd
import numpy as np
import kagglehub
import matplotlib.pyplot as plt

In [5]:
ai_models_price_history = pd.read_csv("/workspaces/ai-model-pricing-analysis-/data/ai_model_price_history.csv")
ai_models_2026 = pd.read_csv("/workspaces/ai-model-pricing-analysis-/data/ai_models_2026.csv")

In [11]:
ai_models_price_history.shape

(167787, 9)

In [10]:
ai_models_price_history.columns

Index(['week_start', 'model_id', 'model_name', 'developer', 'provider', 'mode',
       'input_price_per_1m_tokens', 'output_price_per_1m_tokens',
       'max_input_tokens'],
      dtype='str')

In [13]:
missing_hist_df = (
    ai_models_price_history.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_pct_hist_df = (
    ai_models_price_history.isna()
    .mean()
    .sort_values(ascending=False)
    *100
)

In [15]:
quality_report_hist_df = pd.DataFrame({
    "missing_values": missing_hist_df,
    "missing_%": missing_pct_hist_df
})

quality_report_hist_df

                            missing_values  missing_%
max_input_tokens                     13361   7.963072
output_price_per_1m_tokens            1144   0.681817
input_price_per_1m_tokens             1045   0.622813
model_name                              42   0.025032
week_start                               0   0.000000
provider                                 0   0.000000
developer                                0   0.000000
model_id                                 0   0.000000
mode                                     0   0.000000

In [16]:
ai_models_price_history.duplicated().sum()

ai_models_price_history[ai_models_price_history.duplicated()].head()

Empty DataFrame
Columns: [week_start, model_id, model_name, developer, provider, mode, input_price_per_1m_tokens, output_price_per_1m_tokens, max_input_tokens]
Index: []

In [7]:
ai_models_2026.shape

(4403, 31)